# Cloud Build configuration for Terraform deployment
# This file runs Terraform to create/update Firebase projects

steps:
  # Step 1: Initialize Terraform
  - name: 'hashicorp/terraform:1.6'
    id: 'terraform-init'
    args:
      - 'init'
      - '-reconfigure'
    dir: 'terraform/environments/${_ENVIRONMENT}'
    env:
      - 'TF_VAR_billing_account=${_BILLING_ACCOUNT}'
      - 'TF_VAR_org_id=${_ORG_ID}'

  # Step 2: Validate Terraform configuration
  - name: 'hashicorp/terraform:1.6'
    id: 'terraform-validate'
    args:
      - 'validate'
    dir: 'terraform/environments/${_ENVIRONMENT}'

  # Step 3: Plan Terraform changes
  - name: 'hashicorp/terraform:1.6'
    id: 'terraform-plan'
    args:
      - 'plan'
      - '-out=tfplan'
    dir: 'terraform/environments/${_ENVIRONMENT}'
    env:
      - 'TF_VAR_billing_account=${_BILLING_ACCOUNT}'
      - 'TF_VAR_org_id=${_ORG_ID}'

  # Step 4: Apply Terraform (only on main branch or manual trigger)
  - name: 'hashicorp/terraform:1.6'
    id: 'terraform-apply'
    args:
      - 'apply'
      - '-auto-approve'
      - 'tfplan'
    dir: 'terraform/environments/${_ENVIRONMENT}'
    env:
      - 'TF_VAR_billing_account=${_BILLING_ACCOUNT}'
      - 'TF_VAR_org_id=${_ORG_ID}'

  # Step 5: Output Firebase configuration
  - name: 'hashicorp/terraform:1.6'
    id: 'terraform-output'
    args:
      - 'output'
      - '-json'
    dir: 'terraform/environments/${_ENVIRONMENT}'

# Substitution variables (set these in Cloud Build trigger)
substitutions:
  _ENVIRONMENT: 'dev'
  _BILLING_ACCOUNT: ''  # Set in trigger or command line
  _ORG_ID: ''           # Set in trigger or command line (optional)

# Service account needs these roles:
# - roles/firebase.admin
# - roles/resourcemanager.projectCreator
# - roles/billing.projectManager
# - roles/serviceusage.serviceUsageAdmin

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'

timeout: '1200s'  # 20 minutes
