steps:
  - label: ":jest: Unit Tests"
    command:
      - "npm ci"
      - "npm test -- --run"
    plugins:
      - docker#v3.9.0:
          image: "node:20"

  - label: ":typescript: Type Check"
    command:
      - "npm ci"
      - "npx tsc --noEmit"
    plugins:
      - docker#v3.9.0:
          image: "node:20"

  - label: ":buildkite: Build"
    command:
      - "npm ci"
      - "npm run build"
    plugins:
      - docker#v3.9.0:
          image: "node:20"

  - label: ":playwright: E2E Tests"
    if: "build.branch == 'main'"
    command:
      - "npm ci"
      - "'y' | npx playwright install --with-deps"
      - "CI='true' BUILDKITE_ANALYTICS_TOKEN=$TEST_ANALYTICS_TOKEN npx playwright test"
    plugins:
      - docker#v3.9.0:
          image: "node:20"
          environment:
            - "TEST_ANALYTICS_TOKEN"
