steps:
  - label: ":jest: Unit Tests"
    command:
      - "npm ci"
      - "npm test -- --run"
    plugins:
      - docker#v3.9.0:
          image: "node:20"

  - label: ":typescript: Type Check"
    command:
      - "npm ci"
      - "npx tsc --noEmit"
    plugins:
      - docker#v3.9.0:
          image: "node:20"

  - label: ":buildkite: Build"
    command:
      - "npm ci"
      - "npm run build"
    plugins:
      - docker#v3.9.0:
          image: "node:20"

  - label: ":playwright: E2E Tests"
    if: "build.branch == 'main'"
    command:
      - "npm ci"
      - "npm install playwright@1.56.1 --yes"
      - "npx playwright install --with-deps"
      - "npx playwright test"
    plugins:
      - docker#v3.9.0:
          image: "node:20"